---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-service
  namespace: hello
spec:
  selector:
    matchLabels:
      app: hello-service
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-service
    spec:
      containers:
      - name: hello-service
        image: msathepivotal/hello-service
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: hello-service
  labels:
    app: hello-service
  namespace: hello
spec:
  #type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: hello-service
