# Generated on Wed Aug 14 00:38:14 EDT 2019
kind: Service
apiVersion: v1
metadata:
  name: hello-service
  labels:
    app: hello-service
  namespace: hello

spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: hello-service